### ISSUE TITLE
Runs in Bash but not zsh or fish shells

### ISSUE THREAD

**Issue by Gzoref** [kai-dg/hipposcraper#66]
Runs in Bash but not zsh or fish shells...May just be that I don't have it set up correctly in zsh, but I assume that if it works across different shells, right?
![image](https://user-images.githubusercontent.com/9394859/73019270-4018c800-3df1-11ea-8778-8dcb962fdc12.png)

**Comment by davixcky** [comment]
Check the alias

**Comment by Gzoref** [comment]
[SOLVED] Adding the aliases to teh .zshrc file works!
